//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_transaction()
        {
            this.p_purchase = new HashSet<p_purchase>();
        }
    
        public int transaction_id { get; set; }
        public Nullable<float> total_price { get; set; }
        public Nullable<int> discount_code { get; set; }
        public System.DateTime date { get; set; }
        public int cid { get; set; }
    
        public virtual p_customer p_customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_purchase> p_purchase { get; set; }
    }
}
